name: memeory
description: Memeory mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  url_launcher: ^5.4.1

  dartx: ^0.2.0
  localstorage: ^3.0.0
  shared_preferences: ^0.5.6
  timeago: ^2.0.22
  pedantic: ^1.8.0
  flutter_i18n: ^0.8.2
  share: ^0.6.3

  cupertino_icons: ^0.1.3
  dynamic_theme: ^1.0.1
  chewie: ^0.9.8
  toast: ^0.1.5
  font_awesome_flutter: ^8.5.0
  cached_network_image: ^2.0.0-rc.1
  pull_to_refresh: ^1.5.7
  preload_page_view: ^0.1.4
  carousel_slider: ^1.3.1
  page_transition: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/logo/logo-inverted.png
    - assets/orientation/horizontal.mp4
    - assets/orientation/vertical.mp4
    - assets/i18n/

  fonts:
    - family: Memeory
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

flutter_icons:
  image_path: assets/logo/logo.png
  android: true
  ios: true
