name: memeory
description: Memeory mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  google_sign_in: ^4.0.2

  localstorage: ^2.0.0
  shared_preferences: ^0.5.3+1

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  chewie: ^0.9.7
  toast: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2


flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/orientation/horizontal.mp4
    - assets/orientation/vertical.mp4

  fonts:
    - family: Memeory
      fonts:
        - asset: fonts/BadScript-Regular.ttf

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
