name: memeory
description: Memeory mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  webview_flutter: ^0.3.13
  firebase_auth: 0.14.0+5
  google_sign_in: ^3.2.2
  flutter_facebook_login: ^3.0.0

  localstorage: ^1.3.0
  shared_preferences: ^0.5.3
  timeago: ^2.0.20
  pedantic: ^1.8.0

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  chewie: ^0.9.8
  toast: ^0.1.5
  gradient_text: ^1.0.2
  cached_network_image: ^1.1.1
  pull_to_refresh: ^1.5.6
  preload_page_view: ^0.1.4
  carousel_slider: ^1.3.1
  page_transition: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2


flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/logo/logo-inverted.png
    - assets/orientation/horizontal.mp4
    - assets/orientation/vertical.mp4

  fonts:
    - family: Memeory
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

flutter_icons:
  image_path: assets/logo/logo.png
  android: true
  ios: true
