// Keys
import 'package:flutter/material.dart';

const MEMES_COUNT_ON_THE_PAGE = 50;

const APP_VISIT_DATETIME_KEY = "APP_VISIT_DATETIME";
const SELECTED_CHANNELS_KEY = "CHANNELS";
const SELECTED_ORIENTATION_KEY = "ORIENTATION";
const GOOGLE_PROFILE_KEY = "GOOGLE_PROFILE";
const FACEBOOK_PROFILE_KEY = "FACEBOOK_PROFILE";
const VK_PROFILE_KEY = "VK_PROFILE";

//Light Theme
const INVERTED_TEXT_COLOR_LIGHT = Colors.black38;

//Dark Theme
const INVERTED_TEXT_COLOR_DARK = Colors.white70;
