server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: localdev
  main:
    allow-bean-definition-overriding: true

memeory:
  fetch-interval-ms: 60000
  fetch-count: 100

channel:
  reddit:
    base-url: https://www.reddit.com
  vk:
    app-id: 7024306
    access-token: ceea6953ceea6953ceea6953ecce8147e1cceeaceea695393edbd336b29a7c8ed2d0b91
