server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: localdev,secret
  main:
    allow-bean-definition-overriding: true

memeory:
  fetch-interval-ms: 600000
  fetch-count: 100
  meme-expiration-days: 30

provider:
  reddit:
    enabled: true
    scrape-enabled: false
  vk:
    enabled: true
    scrape-enabled: true
  facebook:
    enabled: true
    scrape-enabled: true
  instagram:
    enabled: true
    scrape-enabled: true
  twitter:
    enabled: true
    scrape-enabled: true
  ninegag:
    enabled: true
    scrape-enabled: true
  pinterest:
    enabled: true
    scrape-enabled: true
