server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: localdev,secret
  main:
    allow-bean-definition-overriding: true

memeory:
  fetch-max-count: 100
  fetch-interval: 5m
  meme-life-time: 10d

provider:
  reddit:
    enabled: true
    scrape-enabled: false
  vk:
    enabled: true
    scrape-enabled: true
  facebook:
    enabled: true
    scrape-enabled: true
  instagram:
    enabled: true
    scrape-enabled: true
  twitter:
    enabled: true
    scrape-enabled: true
  ninegag:
    enabled: true
    scrape-enabled: true
  pinterest:
    enabled: true
    scrape-enabled: true

management:
  health:
    mongo:
      enabled: true
  endpoint:
    beans:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
  info:
    git:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"