server:
  port: 8080
  servlet:
    context-path: /

memeory:
  fetch-interval-ms: 60000

spring:
  profiles:
    active: localdev
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://memeory:memeory@localhost:27017/admin

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    export:
      simple:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
