version: '3.3'
services:
  mongo:
    container_name: memeory-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: memeory
      MONGO_INITDB_ROOT_PASSWORD: memeory
    volumes:
      - /tmp/memeory/mongo:/data/db
